/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 12
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 32
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_PLUS = 1,
  anon_sym_DASH = 2,
  anon_sym_STAR = 3,
  anon_sym_SLASH = 4,
  anon_sym_PIPE_PIPE = 5,
  anon_sym_EQ = 6,
  anon_sym_BANG_EQ = 7,
  anon_sym_LT = 8,
  anon_sym_GT = 9,
  anon_sym_LT_EQ = 10,
  anon_sym_GT_EQ = 11,
  anon_sym_NOT = 12,
  anon_sym_AND = 13,
  anon_sym_OR = 14,
  anon_sym_Function = 15,
  anon_sym_COLON = 16,
  anon_sym_Return = 17,
  anon_sym_Set = 18,
  anon_sym_Call = 19,
  anon_sym_LPAREN = 20,
  anon_sym_RPAREN = 21,
  anon_sym_If = 22,
  anon_sym_Else = 23,
  sym_identifier = 24,
  sym_int_literal = 25,
  anon_sym_DOT = 26,
  sym_measurement = 27,
  sym_single_quoted_string = 28,
  sym_double_quoted_string = 29,
  sym_boolean = 30,
  sym_comment = 31,
  sym_source_file = 32,
  sym__definition = 33,
  sym_operator = 34,
  sym_function_definition = 35,
  sym_set_expression = 36,
  sym_call_expression = 37,
  sym_conditional_expression = 38,
  sym_float_literal = 39,
  aux_sym_source_file_repeat1 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_PIPE_PIPE] = "||",
  [anon_sym_EQ] = "=",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_GT_EQ] = ">=",
  [anon_sym_NOT] = "NOT",
  [anon_sym_AND] = "AND",
  [anon_sym_OR] = "OR",
  [anon_sym_Function] = "Function",
  [anon_sym_COLON] = ":",
  [anon_sym_Return] = "Return",
  [anon_sym_Set] = "Set",
  [anon_sym_Call] = "Call",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_If] = "If",
  [anon_sym_Else] = "Else",
  [sym_identifier] = "identifier",
  [sym_int_literal] = "int_literal",
  [anon_sym_DOT] = ".",
  [sym_measurement] = "measurement",
  [sym_single_quoted_string] = "single_quoted_string",
  [sym_double_quoted_string] = "double_quoted_string",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_operator] = "operator",
  [sym_function_definition] = "function_definition",
  [sym_set_expression] = "set_expression",
  [sym_call_expression] = "call_expression",
  [sym_conditional_expression] = "conditional_expression",
  [sym_float_literal] = "float_literal",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_PIPE_PIPE] = anon_sym_PIPE_PIPE,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_GT_EQ] = anon_sym_GT_EQ,
  [anon_sym_NOT] = anon_sym_NOT,
  [anon_sym_AND] = anon_sym_AND,
  [anon_sym_OR] = anon_sym_OR,
  [anon_sym_Function] = anon_sym_Function,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_Return] = anon_sym_Return,
  [anon_sym_Set] = anon_sym_Set,
  [anon_sym_Call] = anon_sym_Call,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_If] = anon_sym_If,
  [anon_sym_Else] = anon_sym_Else,
  [sym_identifier] = sym_identifier,
  [sym_int_literal] = sym_int_literal,
  [anon_sym_DOT] = anon_sym_DOT,
  [sym_measurement] = sym_measurement,
  [sym_single_quoted_string] = sym_single_quoted_string,
  [sym_double_quoted_string] = sym_double_quoted_string,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_operator] = sym_operator,
  [sym_function_definition] = sym_function_definition,
  [sym_set_expression] = sym_set_expression,
  [sym_call_expression] = sym_call_expression,
  [sym_conditional_expression] = sym_conditional_expression,
  [sym_float_literal] = sym_float_literal,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_NOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_OR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Function] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Return] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Set] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Call] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_If] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Else] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_int_literal] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [sym_measurement] = {
    .visible = true,
    .named = true,
  },
  [sym_single_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_double_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_operator] = {
    .visible = true,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_set_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_call_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_conditional_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_float_literal] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      ADVANCE_MAP(
        '!', 71,
        '"', 2,
        '\'', 3,
        '(', 59,
        ')', 60,
        '*', 42,
        '+', 40,
        '-', 41,
        '.', 66,
        '/', 43,
        ':', 55,
        '<', 47,
        '=', 45,
        '>', 48,
        'A', 8,
        'C', 15,
        'E', 22,
        'F', 4,
        'I', 20,
        'N', 9,
        'O', 10,
        'R', 17,
        'S', 19,
        'T', 11,
        '|', 35,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 1:
      if (lookahead == '!') ADVANCE(72);
      if (lookahead == 'R') ADVANCE(17);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(69);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(68);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == 'A') ADVANCE(7);
      if (lookahead == 'u') ADVANCE(25);
      END_STATE();
    case 5:
      if (lookahead == 'D') ADVANCE(52);
      END_STATE();
    case 6:
      if (lookahead == 'E') ADVANCE(70);
      END_STATE();
    case 7:
      if (lookahead == 'L') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == 'N') ADVANCE(5);
      END_STATE();
    case 9:
      if (lookahead == 'O') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 'R') ADVANCE(53);
      END_STATE();
    case 11:
      if (lookahead == 'R') ADVANCE(14);
      END_STATE();
    case 12:
      if (lookahead == 'S') ADVANCE(6);
      END_STATE();
    case 13:
      if (lookahead == 'T') ADVANCE(51);
      END_STATE();
    case 14:
      if (lookahead == 'U') ADVANCE(6);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(24);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(33);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(62);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(32);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(61);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(58);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(16);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(56);
      END_STATE();
    case 27:
      if (lookahead == 'n') ADVANCE(54);
      END_STATE();
    case 28:
      if (lookahead == 'o') ADVANCE(27);
      END_STATE();
    case 29:
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 30:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 31:
      if (lookahead == 't') ADVANCE(34);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(21);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(29);
      END_STATE();
    case 35:
      if (lookahead == '|') ADVANCE(44);
      END_STATE();
    case 36:
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(36);
      END_STATE();
    case 38:
      if (eof) ADVANCE(39);
      if (lookahead == '!') ADVANCE(72);
      if (lookahead == '(') ADVANCE(59);
      if (lookahead == ')') ADVANCE(60);
      if (lookahead == ':') ADVANCE(55);
      if (lookahead == '=') ADVANCE(45);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_PIPE_PIPE);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '=') ADVANCE(49);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_GT);
      if (lookahead == '=') ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_GT_EQ);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_NOT);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_AND);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_OR);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_Function);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_Return);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_Set);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_Call);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_If);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_Else);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_int_literal);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '"' ||
          lookahead == '\'') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_int_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_measurement);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_single_quoted_string);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_double_quoted_string);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_boolean);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '=') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(72);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 38},
  [13] = {.lex_state = 38},
  [14] = {.lex_state = 38},
  [15] = {.lex_state = 38},
  [16] = {.lex_state = 38},
  [17] = {.lex_state = 38},
  [18] = {.lex_state = 38},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 38},
  [21] = {.lex_state = 38},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_PIPE_PIPE] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_GT_EQ] = ACTIONS(1),
    [anon_sym_NOT] = ACTIONS(1),
    [anon_sym_AND] = ACTIONS(1),
    [anon_sym_OR] = ACTIONS(1),
    [anon_sym_Function] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_Return] = ACTIONS(1),
    [anon_sym_Set] = ACTIONS(1),
    [anon_sym_Call] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_If] = ACTIONS(1),
    [anon_sym_Else] = ACTIONS(1),
    [sym_int_literal] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [sym_measurement] = ACTIONS(1),
    [sym_single_quoted_string] = ACTIONS(1),
    [sym_double_quoted_string] = ACTIONS(1),
    [sym_boolean] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(15),
    [sym__definition] = STATE(2),
    [sym_operator] = STATE(2),
    [sym_function_definition] = STATE(2),
    [sym_set_expression] = STATE(2),
    [sym_call_expression] = STATE(2),
    [sym_conditional_expression] = STATE(2),
    [sym_float_literal] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
    [anon_sym_NOT] = ACTIONS(7),
    [anon_sym_AND] = ACTIONS(7),
    [anon_sym_OR] = ACTIONS(7),
    [anon_sym_Function] = ACTIONS(11),
    [anon_sym_Set] = ACTIONS(13),
    [anon_sym_Call] = ACTIONS(15),
    [anon_sym_If] = ACTIONS(17),
    [sym_int_literal] = ACTIONS(19),
    [sym_measurement] = ACTIONS(21),
    [sym_single_quoted_string] = ACTIONS(21),
    [sym_double_quoted_string] = ACTIONS(21),
    [sym_boolean] = ACTIONS(21),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym__definition] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_set_expression] = STATE(3),
    [sym_call_expression] = STATE(3),
    [sym_conditional_expression] = STATE(3),
    [sym_float_literal] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_PLUS] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(7),
    [anon_sym_STAR] = ACTIONS(7),
    [anon_sym_SLASH] = ACTIONS(7),
    [anon_sym_PIPE_PIPE] = ACTIONS(7),
    [anon_sym_EQ] = ACTIONS(7),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_LT] = ACTIONS(9),
    [anon_sym_GT] = ACTIONS(9),
    [anon_sym_LT_EQ] = ACTIONS(7),
    [anon_sym_GT_EQ] = ACTIONS(7),
    [anon_sym_NOT] = ACTIONS(7),
    [anon_sym_AND] = ACTIONS(7),
    [anon_sym_OR] = ACTIONS(7),
    [anon_sym_Function] = ACTIONS(11),
    [anon_sym_Set] = ACTIONS(13),
    [anon_sym_Call] = ACTIONS(15),
    [anon_sym_If] = ACTIONS(17),
    [sym_int_literal] = ACTIONS(19),
    [sym_measurement] = ACTIONS(25),
    [sym_single_quoted_string] = ACTIONS(25),
    [sym_double_quoted_string] = ACTIONS(25),
    [sym_boolean] = ACTIONS(25),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(3)] = {
    [sym__definition] = STATE(3),
    [sym_operator] = STATE(3),
    [sym_function_definition] = STATE(3),
    [sym_set_expression] = STATE(3),
    [sym_call_expression] = STATE(3),
    [sym_conditional_expression] = STATE(3),
    [sym_float_literal] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_DASH] = ACTIONS(29),
    [anon_sym_STAR] = ACTIONS(29),
    [anon_sym_SLASH] = ACTIONS(29),
    [anon_sym_PIPE_PIPE] = ACTIONS(29),
    [anon_sym_EQ] = ACTIONS(29),
    [anon_sym_BANG_EQ] = ACTIONS(32),
    [anon_sym_LT] = ACTIONS(32),
    [anon_sym_GT] = ACTIONS(32),
    [anon_sym_LT_EQ] = ACTIONS(29),
    [anon_sym_GT_EQ] = ACTIONS(29),
    [anon_sym_NOT] = ACTIONS(29),
    [anon_sym_AND] = ACTIONS(29),
    [anon_sym_OR] = ACTIONS(29),
    [anon_sym_Function] = ACTIONS(35),
    [anon_sym_Set] = ACTIONS(38),
    [anon_sym_Call] = ACTIONS(41),
    [anon_sym_If] = ACTIONS(44),
    [sym_int_literal] = ACTIONS(47),
    [sym_measurement] = ACTIONS(50),
    [sym_single_quoted_string] = ACTIONS(50),
    [sym_double_quoted_string] = ACTIONS(50),
    [sym_boolean] = ACTIONS(50),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(4)] = {
    [ts_builtin_sym_end] = ACTIONS(53),
    [anon_sym_PLUS] = ACTIONS(53),
    [anon_sym_DASH] = ACTIONS(53),
    [anon_sym_STAR] = ACTIONS(53),
    [anon_sym_SLASH] = ACTIONS(53),
    [anon_sym_PIPE_PIPE] = ACTIONS(53),
    [anon_sym_EQ] = ACTIONS(53),
    [anon_sym_BANG_EQ] = ACTIONS(55),
    [anon_sym_LT] = ACTIONS(55),
    [anon_sym_GT] = ACTIONS(55),
    [anon_sym_LT_EQ] = ACTIONS(53),
    [anon_sym_GT_EQ] = ACTIONS(53),
    [anon_sym_NOT] = ACTIONS(53),
    [anon_sym_AND] = ACTIONS(53),
    [anon_sym_OR] = ACTIONS(53),
    [anon_sym_Function] = ACTIONS(53),
    [anon_sym_Set] = ACTIONS(53),
    [anon_sym_Call] = ACTIONS(53),
    [anon_sym_If] = ACTIONS(53),
    [anon_sym_Else] = ACTIONS(57),
    [sym_int_literal] = ACTIONS(55),
    [sym_measurement] = ACTIONS(53),
    [sym_single_quoted_string] = ACTIONS(53),
    [sym_double_quoted_string] = ACTIONS(53),
    [sym_boolean] = ACTIONS(53),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(5)] = {
    [ts_builtin_sym_end] = ACTIONS(59),
    [anon_sym_PLUS] = ACTIONS(59),
    [anon_sym_DASH] = ACTIONS(59),
    [anon_sym_STAR] = ACTIONS(59),
    [anon_sym_SLASH] = ACTIONS(59),
    [anon_sym_PIPE_PIPE] = ACTIONS(59),
    [anon_sym_EQ] = ACTIONS(59),
    [anon_sym_BANG_EQ] = ACTIONS(61),
    [anon_sym_LT] = ACTIONS(61),
    [anon_sym_GT] = ACTIONS(61),
    [anon_sym_LT_EQ] = ACTIONS(59),
    [anon_sym_GT_EQ] = ACTIONS(59),
    [anon_sym_NOT] = ACTIONS(59),
    [anon_sym_AND] = ACTIONS(59),
    [anon_sym_OR] = ACTIONS(59),
    [anon_sym_Function] = ACTIONS(59),
    [anon_sym_Set] = ACTIONS(59),
    [anon_sym_Call] = ACTIONS(59),
    [anon_sym_If] = ACTIONS(59),
    [sym_int_literal] = ACTIONS(61),
    [anon_sym_DOT] = ACTIONS(63),
    [sym_measurement] = ACTIONS(59),
    [sym_single_quoted_string] = ACTIONS(59),
    [sym_double_quoted_string] = ACTIONS(59),
    [sym_boolean] = ACTIONS(59),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(6)] = {
    [ts_builtin_sym_end] = ACTIONS(65),
    [anon_sym_PLUS] = ACTIONS(65),
    [anon_sym_DASH] = ACTIONS(65),
    [anon_sym_STAR] = ACTIONS(65),
    [anon_sym_SLASH] = ACTIONS(65),
    [anon_sym_PIPE_PIPE] = ACTIONS(65),
    [anon_sym_EQ] = ACTIONS(65),
    [anon_sym_BANG_EQ] = ACTIONS(67),
    [anon_sym_LT] = ACTIONS(67),
    [anon_sym_GT] = ACTIONS(67),
    [anon_sym_LT_EQ] = ACTIONS(65),
    [anon_sym_GT_EQ] = ACTIONS(65),
    [anon_sym_NOT] = ACTIONS(65),
    [anon_sym_AND] = ACTIONS(65),
    [anon_sym_OR] = ACTIONS(65),
    [anon_sym_Function] = ACTIONS(65),
    [anon_sym_Set] = ACTIONS(65),
    [anon_sym_Call] = ACTIONS(65),
    [anon_sym_If] = ACTIONS(65),
    [sym_int_literal] = ACTIONS(67),
    [sym_measurement] = ACTIONS(65),
    [sym_single_quoted_string] = ACTIONS(65),
    [sym_double_quoted_string] = ACTIONS(65),
    [sym_boolean] = ACTIONS(65),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(7)] = {
    [ts_builtin_sym_end] = ACTIONS(69),
    [anon_sym_PLUS] = ACTIONS(69),
    [anon_sym_DASH] = ACTIONS(69),
    [anon_sym_STAR] = ACTIONS(69),
    [anon_sym_SLASH] = ACTIONS(69),
    [anon_sym_PIPE_PIPE] = ACTIONS(69),
    [anon_sym_EQ] = ACTIONS(69),
    [anon_sym_BANG_EQ] = ACTIONS(71),
    [anon_sym_LT] = ACTIONS(71),
    [anon_sym_GT] = ACTIONS(71),
    [anon_sym_LT_EQ] = ACTIONS(69),
    [anon_sym_GT_EQ] = ACTIONS(69),
    [anon_sym_NOT] = ACTIONS(69),
    [anon_sym_AND] = ACTIONS(69),
    [anon_sym_OR] = ACTIONS(69),
    [anon_sym_Function] = ACTIONS(69),
    [anon_sym_Set] = ACTIONS(69),
    [anon_sym_Call] = ACTIONS(69),
    [anon_sym_If] = ACTIONS(69),
    [sym_int_literal] = ACTIONS(71),
    [sym_measurement] = ACTIONS(69),
    [sym_single_quoted_string] = ACTIONS(69),
    [sym_double_quoted_string] = ACTIONS(69),
    [sym_boolean] = ACTIONS(69),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(8)] = {
    [ts_builtin_sym_end] = ACTIONS(73),
    [anon_sym_PLUS] = ACTIONS(73),
    [anon_sym_DASH] = ACTIONS(73),
    [anon_sym_STAR] = ACTIONS(73),
    [anon_sym_SLASH] = ACTIONS(73),
    [anon_sym_PIPE_PIPE] = ACTIONS(73),
    [anon_sym_EQ] = ACTIONS(73),
    [anon_sym_BANG_EQ] = ACTIONS(75),
    [anon_sym_LT] = ACTIONS(75),
    [anon_sym_GT] = ACTIONS(75),
    [anon_sym_LT_EQ] = ACTIONS(73),
    [anon_sym_GT_EQ] = ACTIONS(73),
    [anon_sym_NOT] = ACTIONS(73),
    [anon_sym_AND] = ACTIONS(73),
    [anon_sym_OR] = ACTIONS(73),
    [anon_sym_Function] = ACTIONS(73),
    [anon_sym_Set] = ACTIONS(73),
    [anon_sym_Call] = ACTIONS(73),
    [anon_sym_If] = ACTIONS(73),
    [sym_int_literal] = ACTIONS(75),
    [sym_measurement] = ACTIONS(73),
    [sym_single_quoted_string] = ACTIONS(73),
    [sym_double_quoted_string] = ACTIONS(73),
    [sym_boolean] = ACTIONS(73),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(77),
    [anon_sym_PLUS] = ACTIONS(77),
    [anon_sym_DASH] = ACTIONS(77),
    [anon_sym_STAR] = ACTIONS(77),
    [anon_sym_SLASH] = ACTIONS(77),
    [anon_sym_PIPE_PIPE] = ACTIONS(77),
    [anon_sym_EQ] = ACTIONS(77),
    [anon_sym_BANG_EQ] = ACTIONS(79),
    [anon_sym_LT] = ACTIONS(79),
    [anon_sym_GT] = ACTIONS(79),
    [anon_sym_LT_EQ] = ACTIONS(77),
    [anon_sym_GT_EQ] = ACTIONS(77),
    [anon_sym_NOT] = ACTIONS(77),
    [anon_sym_AND] = ACTIONS(77),
    [anon_sym_OR] = ACTIONS(77),
    [anon_sym_Function] = ACTIONS(77),
    [anon_sym_Set] = ACTIONS(77),
    [anon_sym_Call] = ACTIONS(77),
    [anon_sym_If] = ACTIONS(77),
    [sym_int_literal] = ACTIONS(79),
    [sym_measurement] = ACTIONS(77),
    [sym_single_quoted_string] = ACTIONS(77),
    [sym_double_quoted_string] = ACTIONS(77),
    [sym_boolean] = ACTIONS(77),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(10)] = {
    [ts_builtin_sym_end] = ACTIONS(81),
    [anon_sym_PLUS] = ACTIONS(81),
    [anon_sym_DASH] = ACTIONS(81),
    [anon_sym_STAR] = ACTIONS(81),
    [anon_sym_SLASH] = ACTIONS(81),
    [anon_sym_PIPE_PIPE] = ACTIONS(81),
    [anon_sym_EQ] = ACTIONS(81),
    [anon_sym_BANG_EQ] = ACTIONS(83),
    [anon_sym_LT] = ACTIONS(83),
    [anon_sym_GT] = ACTIONS(83),
    [anon_sym_LT_EQ] = ACTIONS(81),
    [anon_sym_GT_EQ] = ACTIONS(81),
    [anon_sym_NOT] = ACTIONS(81),
    [anon_sym_AND] = ACTIONS(81),
    [anon_sym_OR] = ACTIONS(81),
    [anon_sym_Function] = ACTIONS(81),
    [anon_sym_Set] = ACTIONS(81),
    [anon_sym_Call] = ACTIONS(81),
    [anon_sym_If] = ACTIONS(81),
    [sym_int_literal] = ACTIONS(83),
    [sym_measurement] = ACTIONS(81),
    [sym_single_quoted_string] = ACTIONS(81),
    [sym_double_quoted_string] = ACTIONS(81),
    [sym_boolean] = ACTIONS(81),
    [sym_comment] = ACTIONS(3),
  },
  [STATE(11)] = {
    [ts_builtin_sym_end] = ACTIONS(85),
    [anon_sym_PLUS] = ACTIONS(85),
    [anon_sym_DASH] = ACTIONS(85),
    [anon_sym_STAR] = ACTIONS(85),
    [anon_sym_SLASH] = ACTIONS(85),
    [anon_sym_PIPE_PIPE] = ACTIONS(85),
    [anon_sym_EQ] = ACTIONS(85),
    [anon_sym_BANG_EQ] = ACTIONS(87),
    [anon_sym_LT] = ACTIONS(87),
    [anon_sym_GT] = ACTIONS(87),
    [anon_sym_LT_EQ] = ACTIONS(85),
    [anon_sym_GT_EQ] = ACTIONS(85),
    [anon_sym_NOT] = ACTIONS(85),
    [anon_sym_AND] = ACTIONS(85),
    [anon_sym_OR] = ACTIONS(85),
    [anon_sym_Function] = ACTIONS(85),
    [anon_sym_Set] = ACTIONS(85),
    [anon_sym_Call] = ACTIONS(85),
    [anon_sym_If] = ACTIONS(85),
    [sym_int_literal] = ACTIONS(87),
    [sym_measurement] = ACTIONS(85),
    [sym_single_quoted_string] = ACTIONS(85),
    [sym_double_quoted_string] = ACTIONS(85),
    [sym_boolean] = ACTIONS(85),
    [sym_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(89), 1,
      anon_sym_COLON,
    ACTIONS(91), 1,
      sym_comment,
  [7] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(93), 1,
      sym_identifier,
  [14] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(95), 1,
      sym_identifier,
  [21] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
  [28] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(99), 1,
      sym_identifier,
  [35] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(101), 1,
      anon_sym_EQ,
  [42] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(103), 1,
      anon_sym_LPAREN,
  [49] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(105), 1,
      anon_sym_Return,
  [56] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(107), 1,
      anon_sym_RPAREN,
  [63] = 2,
    ACTIONS(91), 1,
      sym_comment,
    ACTIONS(109), 1,
      sym_int_literal,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(12)] = 0,
  [SMALL_STATE(13)] = 7,
  [SMALL_STATE(14)] = 14,
  [SMALL_STATE(15)] = 21,
  [SMALL_STATE(16)] = 28,
  [SMALL_STATE(17)] = 35,
  [SMALL_STATE(18)] = 42,
  [SMALL_STATE(19)] = 49,
  [SMALL_STATE(20)] = 56,
  [SMALL_STATE(21)] = 63,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [35] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [44] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_expression, 1, 0, 0),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_expression, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__definition, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operator, 1, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operator, 1, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_float_literal, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_float_literal, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conditional_expression, 2, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conditional_expression, 2, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_set_expression, 3, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_set_expression, 3, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 4, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_call_expression, 4, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_call_expression, 4, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [97] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_gupta(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "gupta",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
